### ISSUE TITLE
.safeApply() throws if the second arg is not a function

### ISSUE THREAD

**Issue by sirbarrence** [Reactive-Extensions/rx.angular.js#104]
If I call `.safeApply($scope)` without a function for the second argument, an exception is thrown because `noop` is not defined. (In the 1.0 refactor, `noop` was removed.)

Granted, this helped me find bugs in my code, because I almost never want to invoke `.safeApply()` without a second arg ;)

**Comment by mattpodwysocki** [comment]
Fixed as per 1.0.2
