### ISSUE TITLE
Some remarks on the doc

### ISSUE THREAD

**Issue by PhiLhoSoft** [Reactive-Extensions/rx.angular.js#107]
Referring to https://github.com/Reactive-Extensions/rx.angular.js/tree/master/docs

- In the summary, I read `'$toObservable'` not in code style like the other. Looks like you used single quotes instead of back ticks.
- `observeOnScope` and `$toObservable` have an optional `objectEquality` parameter documented as being a (Function) but it is actually a boolean.
- digest()'s example is syntactically incorrect (missing a closing parenthesis). Not sure of how / when to use this function...
- `$createObservableFunction`: listener parameter should be marked as optional (it is omitted in the example).
- Looking at the source, I see other functions: `$toObservableCollection`, `$toObservableGroup`. I suggest to document them...
- [Update] Also found `rx.createObservableFunction` in https://github.com/Reactive-Extensions/rx.angular.js/blob/master/examples/%24createObservableFunctionAsController/app.js Too useful not to be documented... :smile: 

General remark: not sure if there is a difference between `observeOnScope` and `$toObservable`. BTW, why the former must be injected separately?

**Comment by sirbarrence** [comment]
There's a pencil button in the top right corner of .md files in the repo that makes it really easy to make quick corrections and submit a pull request for simple typos like these, all from the browser. I've had many doc corrections accepted this way.

**Comment by PhiLhoSoft** [comment]
@sirbarrence False feeling of simplicity... :smile: 
This isn't a wiki, clicking on this pencil will fork the project and we must do all the complex and lengthly dance of GitHub PRs to propose a change.
Beside, if there are typos indeed easy to fix, I expected some feedback on some of my remarks.
That said, I am willing to do the above dance to fix some things. I suppose I can go ahead, do some fixes, hoping they are OK.

BTW, I don't know if one can easily cherry-pick some changes while rejecting others (line per line) in a GH PR.

**Comment by mattpodwysocki** [comment]
Closing as per work by @sirbarrence
