### ISSUE TITLE
Why is ScopeScheduler gone?

### ISSUE THREAD

**Issue by bytenik** [Reactive-Extensions/rx.angular.js#110]
In commit 8d6a3ab1a81617dd36d4c1c36d317adc91519a8d you guys removed ScopeScheduler. Why? We used it here at FunnelFire. Is there a replacement?

**Comment by Roaders** [comment]
I am wondering this as well.

**Comment by mattpodwysocki** [comment]
Re-added ScopeScheduler for latest version
