### ISSUE TITLE
Examples are broken with the rx.js version that is defined in html files

### ISSUE THREAD

**Issue by zilvinasu** [Reactive-Extensions/rx.angular.js#120]
For all of the examples when trying to run them, rx.js throws me following TypeError. Upgrading rx.js in the examples seems to fix all the problems for me.

<img width="720" alt="screen shot 2015-12-13 at 18 57 39" src="https://cloud.githubusercontent.com/assets/1578440/11768228/d5913138-a1ce-11e5-9fa6-b01f3344b99d.png">

**Comment by chrissun-gs** [comment]
Agree with the previous comment.  Examples were broken with RxJs 2.2.27.
I changed the URL for rx.all.js to use version 4.0.7 and things worked.

**Comment by mattpodwysocki** [comment]
Closing as per fix
