### ISSUE TITLE
Replacement for ScopeScheduler in RxJs 4.0

### ISSUE THREAD

**Issue by Roaders** [Reactive-Extensions/rx.angular.js#123]
Hi

I was using Scope Scheduler in my app to ensure that when an observable pushes a new message or completes an angular apply takes place.
I have now upgraded to rxjs 4.0 and this functionality no longer seems to work and in the latest rx.angular.js the scope schedular has been removed.
How do I solve this problem in Rxjs 4.0?

Many Thanks

**Comment by mattpodwysocki** [comment]
Closed as now implemented again
