### ISSUE TITLE
Could safeApply be wrapped within a custom Scheduler?

### ISSUE THREAD

**Issue by marcuswhit** [Reactive-Extensions/rx.angular.js#36]
I'm not sure if there's technical limitations to this, but it seems to me that safeApply seems a bit similar to what I'd expect a scheduler to do.

Thinking more in regular Rx terms, it'd be ideal, and result with cleaner code, if we could have the following:

```
var scopeScheduler = new ScopeScheduler($scope);
myStream
    .timeout(5000)
    .observeOn(scopeScheduler)
    .subscribe(function() {
        // code here will run on correct scope
    });
```

Thoughts?

**Comment by Roaders** [comment]
This solution is exactly what I want to fix my app not updating when I create an observable using fromPromise.
I notice that the scopeScheduler file was removed in commit 8d6a3ab1a81617dd36d4c1c36d317adc91519a8d. What is the recommended solution for this now?
