### ISSUE TITLE
gulp + Browserify: Cannot find module angular.

### ISSUE THREAD

**Issue by BerkeleyTrue** [Reactive-Extensions/rx.angular.js#44]
Using browserify in gulp. Not sure where to take this. Tried using browserify-shim but it doesn't seem to work when using browserify programmatically.

**Comment by ulrikaugustsson** [comment]
#74 Solves this

**Comment by Willmo36** [comment]
This still seems to be an issue. 

`module.exports = factory(root, module.exports, require('rx'), require('angular'));`

`require('angular')` is return an empty object. There for `var rxModule = angular.module('rx', []);` is failing as `module` is undefined. 

I am using both angular and rx-angular from npm. Bundling with browserify and gulp and have tried with browserify-shim.
