### ISSUE TITLE
RxJS Lite

### ISSUE THREAD

**Issue by majgis** [Reactive-Extensions/rx.angular.js#85]
I want to use RxJS Lite. 

Would adding support for rx as a peer dependency solve this issue?

**Comment by mattpodwysocki** [comment]
@majgis no, but I will make a separate build for it

**Comment by majgis** [comment]
Thank you.  I ended up using some postinstall hackery to do it, so I will make sure to use the new build.

**Comment by mattpodwysocki** [comment]
@majgis fixed as per 1.0.4 with rx-lite-angular and rx-lite-angular-compat
