### ISSUE TITLE
createObservableFunction in services

### ISSUE THREAD

**Issue by raysuelzer** [Reactive-Extensions/rx.angular.js#89]
I'm sure I am missing something here, but do you need to inject $scope in order to access createObservableFunction in angular services?

**Comment by mickdelaney** [comment]
https://github.com/Reactive-Extensions/rx.angular.js/blob/master/examples/%24createObservableFunctionAsController/app.js

**Comment by mickdelaney** [comment]
line 30

**Comment by raysuelzer** [comment]
Ah thank you!  the nuget package didn't seem to include this.
