### ISSUE TITLE
rxjs 3.1.1 version breaks zipArray

### ISSUE THREAD

**Issue by krumax** [Reactive-Extensions/rx.angular.js#91]
I have only provided rx.angular.js in my bower.json without providing the rxjs. rx.angular.js also obviously does not pin the rxjs version, so with rxjs 3.1.1 zipArray does not work anymore. A workaround was to pin rxjs to 3.0.1 additionally in my rx.angular.js to have a stable version. But actually that's not the best way relying on rxjs without any version dependency. Could you please have that in mind? Thanks guys!

**Comment by mattpodwysocki** [comment]
@krumax closing as per new release with `zipArray` also being deprecated
