### ISSUE TITLE
Time for a new tagged version?

### ISSUE THREAD

**Issue by robations** [Reactive-Extensions/rx.angular.js#98]
There is some code in the current master I'm keen to use, but the last tagged version was from March this year. Is there a policy on releases, or is this just done on an ad hoc basis? Willing to help if there is anything that can be easily picked up.

**Comment by PhiLhoSoft** [comment]
https://github.com/Reactive-Extensions/rx.angular.js/releases/tag/v1.0.0 has been released 4 days ago... :smile: 
Although my first try has problems.

**Comment by mattpodwysocki** [comment]
@PhiLhoSoft it had errors that were somehow not caught in our unit tests. Apologies. Upgrade to v1.0.1

**Comment by robations** [comment]
Thanks gents.
